name: Build and Upload Lambda   

on:
  #push:
    branches:
      - main
      - dev

env:
  AWS_REGION: ap-south-1
  ENV_NAME: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
  S3_BUCKET: lambda-code-bucket19-${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Zip Utility
      run: sudo apt-get install zip -y

    - name: Create Lambda Zip
      run: zip lambda_function.zip index.js

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Check if S3 Bucket Exists
      id: check-bucket
      continue-on-error: true
      run: |
        aws s3api head-bucket --bucket ${{ env.S3_BUCKET }} 2>/dev/null && echo "exists=true" >> $GITHUB_ENV || echo "exists=false" >> $GITHUB_ENV

    - name: Create S3 Bucket (If Not Exists)
      if: env.exists == 'false'
      run: |
        aws s3api create-bucket --bucket ${{ env.S3_BUCKET }} --region ${{ env.AWS_REGION }} --create-bucket-configuration LocationConstraint=${{ env.AWS_REGION }}

    - name: Upload ZIP to S3
      run: aws s3 cp lambda_function.zip s3://${{ env.S3_BUCKET }}/lambda_function.zip

    - name: Trigger Infra Repo Deployment
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
        -H "Content-Type: application/json" \
        -d '{"event_type": "trigger-from-app-repo"}' \
        https://api.github.com/repos/deva9017/infra-repo/dispatches
